automountToken: false
image:
  repository: staloosh/litecoin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ports:
  name: custom
  containerPort: 9333
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}
  name: "litecoinsa"

securityContext: 
   capabilities:
     drop:
     - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: custom
  name: custom-service-port

fullnameOverride: "litecoin-app"

resources:
   limits:
     cpu: 2000m
     memory: 2560Mi
   requests:
     cpu: 1000m
     memory: 2048Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

namespace: crypto

test:
  name: netcat
  image: nicolaka/netshoot

tcpSocket:
  port: 9333
           
volumeClaim:
  storage: 10Gi
