automountToken: false
image:
  repository: staloosh/litecoin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ports:
  name: custom
  containerPort: 9333
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}
  name: "litecoinsa"

podSecurityContext:
  fsGroup: 1555

securityContext:
   runAsUser: 1555
   runAsGroup: 1555
   privileged: false
   allowPrivilegeEscalation: false
   capabilities:
     drop:
     - ALL

args: "-datadir=/data"

service:
  type: ClusterIP
  port: 80
  targetPort: custom
  name: custom-service-port

fullnameOverride: "litecoin-app"

resources:
   limits:
     cpu: 2000m
     memory: 2560Mi
   requests:
     cpu: 1000m
     memory: 2048Mi

namespace: crypto

test:
  name: netcat
  image: nicolaka/netshoot

tcpSocket:
  port: 9333
           
volumeClaim:
  storage: 10Gi
